### PR TITLE
MNT: slaclab -> pcdshub

### LINKED ISSUE #17: Update repository location
Repository was migrated to pcdshub from slaclab. All references should be updated to that:

Was: https://github.com/slaclab/pytmc
Now: https://github.com/pcdshub/pytmc

### PR DESCRIPTION
**Pull request by klauer**
Closes #17 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]

**Comment by ZLLentz** [comment]
CI fails with `SHA256 mismatch: '9c1d9c26c62778211152245c347959812476f376fb75fb40f14f411ccf9c34d2' != 'e408cc34d5a56ce149cc98c1843da2f99a795586c48dc1ef7431171d5b2611fa'`
Was this supposed to be part of the re-render, or do we need to update the SHA manually in the recipe? I assume this is related to the repository migration

**Comment by klauer** [comment]
The SHA shouldn't have changed... 😕

**Comment by klauer** [comment]
I think the test failure was in error: `9c1d9c26c62778211152245c347959812476f376fb75fb40f14f411ccf9c34d2` is what I get for both archives (slaclab, pcdshub)

**Comment by klauer** [comment]
Looks like I swapped the SHAs in my head. It has indeed changed.

**Comment by hhslepicka** [comment]
It is more likely that the `sha` changed before and it is not related with the change of ownership. The other repo that was migrated worked fine.

**Review by ZLLentz — APPROVED** [review]

**Comment by klauer** [comment]
I'd guess it's the same issue you had previously encountered @hhslepicka 

For psdm_qs_cli, I had a local copy of the old archive I could compare with the new one:
image

A little concerning, but at least it's not a malicious actor hijacking our packages. Merging.

**Pull request merged**
